### ISSUE TITLE
Diagram Examples in Readme file.

### ISSUE THREAD

**Issue by mzargham** [danlessa/cadCAD_diagram#1]
Diagrams are based on visualizing this
![image](https://user-images.githubusercontent.com/10465438/90672484-097e2100-e20b-11ea-8e12-9f6cd61db313.png)
from this documentation
https://github.com/cadCAD-org/cadCAD/tree/master/documentation

we should have a references to the documentation as well as an example of this modules output.

**Comment by danlessa** [comment]
Done
